services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PORT: 8000
      GIN_MODE: release
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:6.2
    tmpfs:
      - /data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 6
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker